### ISSUE TITLE
Stylemark.yml file throwing parsing issues

### ISSUE THREAD

**Issue by feebala** [nextbigsoundinc/stylemark#27]
I'm getting this error (variations of it - depending on the code line) while setting up the styleguide:

`YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 10`

This happens even when I copy-paste the stylemark config example straight from the docs here. Any ideas why? 

I've done a process of elimination with the configuration file, it works if I eliminate all config points except the 'name' which is a single line. I looked closely for any tabs or extra/missing spaces that YAML wouldn't accept, and haven't found anything. 

Here's my bare-minimum settings file:

```
name: App Styles

sidebar: 
	background: "#3b2a55"
	textColor: "#fff"

headHtml: 
	<link rel="stylesheet" href="../css/styles.css">
```

**Comment by feebala** [comment]
I figured it out:
1) I removed line breaks
2) I replaced the tabbed indents with spaces

**Comment by mpetrovich** [comment]
You also need a pipe `|` for multiline blocks like `headHtml`. From the [example](https://github.com/nextbigsoundinc/stylemark#example):
```yaml
sidebar:
  background: "#3b2a55"
  textColor: "#fff"

headHtml: |
  <link rel="stylesheet" href="dist/css/bootstrap.min.css">
```
